# Generated by Django 5.2 on 2025-04-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Superadmin', 'Superadmin')], max_length=20),
        ),
    ]
