# Generated by Django 5.2 on 2025-04-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'MyUser', 'verbose_name_plural': 'MyUsers'},
        ),
    ]
